name: button_multiselect
description: create a list of multiselect buttons that receives a list of items with a generic property that will be returned in the onSelectedChanged event if the item is selected.
version: 0.0.2
homepage: https://github.com/julioamadortejeda/button_multiselect
issue_tracker: https://github.com/julioamadortejeda/button_multiselect/issues

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  auto_size_text: ^3.0.0
  provider: ^6.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
